name: Deploy Vite site to GitHub Pages

on:
  push:
    branches: [ main ]

# Necesario para que la acción pueda crear/actualizar la rama gh-pages
permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build (Vite)
        run: npm run build

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./dist
          # Opcionales:
          # force_orphan: true
          # user_name: github-actions[bot]
          # user_email: 41898282+github-actions[bot]@users.noreply.github.com